In [4]:
import numpy as np

In [5]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [6]:
mylist = [[1,2,3],[3,4,5],[6,7,8]]

In [7]:
np.array(mylist)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [12]:
np.random.randint(1,10,10)

array([7, 3, 7, 8, 5, 4, 8, 8, 3, 6], dtype=int32)

In [13]:
np.random.binomial(1,2,3)

ValueError: p < 0, p > 1 or p is NaN

In [14]:
import numpy as np
myarray = np.linspace(0,10,101)

In [15]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [16]:
array = np.arange(0,11)

In [17]:
array[:3] = 2

In [18]:
array_copy = array.copy()

In [19]:
array

array([ 2,  2,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
nex = array_copy[array >4]

In [21]:
array_copy

array([ 2,  2,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
array_copy  < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False])

In [23]:
array_2d = np.array([[3,4,5],[6,7,8],[9,10,11]])

In [24]:
array_2d[2]

array([ 9, 10, 11])

In [25]:
array_2d[::-1]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5]])

In [26]:
#numpy_operation

In [29]:
arr = np.arange(0,10)

In [30]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
arr - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [33]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [36]:
arr/arr

C:\Users\user\AppData\Local\Temp\ipykernel_16964\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [39]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [41]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [42]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [43]:
np.log(arr)

C:\Users\user\AppData\Local\Temp\ipykernel_16964\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [48]:
arr = np.arange(10)

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr.sum()

np.int64(45)

In [52]:
arr.max()

np.int64(9)

In [53]:
arr.min()

np.int64(0)

In [55]:
arr.std()

np.float64(2.8722813232690143)

In [60]:
arr2d = np.arange(25).reshape(5,5)

In [62]:
arr2d.shape

(5, 5)

In [64]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
arr2d.sum(axis = 0)

array([50, 55, 60, 65, 70])