In [4]:
import numpy as np

In [5]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [6]:
mylist = [[1,2,3],[3,4,5],[6,7,8]]

In [7]:
np.array(mylist)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [12]:
np.random.randint(1,10,10)

array([7, 3, 7, 8, 5, 4, 8, 8, 3, 6], dtype=int32)

In [13]:
np.random.binomial(1,2,3)

ValueError: p < 0, p > 1 or p is NaN

In [14]:
import numpy as np
myarray = np.linspace(0,10,101)

In [15]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [16]:
array = np.arange(0,11)

In [17]:
array[:3] = 2

In [18]:
array_copy = array.copy()

In [19]:
array

array([ 2,  2,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
nex = array_copy[array >4]

In [21]:
array_copy

array([ 2,  2,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
array_copy  < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False])

In [23]:
array_2d = np.array([[3,4,5],[6,7,8],[9,10,11]])

In [24]:
array_2d[2]

array([ 9, 10, 11])

In [25]:
array_2d[::-1]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5]])

In [26]:
#numpy_operation

In [29]:
arr = np.arange(0,10)

In [30]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
arr - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [33]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [36]:
arr/arr

C:\Users\user\AppData\Local\Temp\ipykernel_16964\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [39]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [41]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [42]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [43]:
np.log(arr)

C:\Users\user\AppData\Local\Temp\ipykernel_16964\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [48]:
arr = np.arange(10)

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr.sum()

np.int64(45)

In [52]:
arr.max()

np.int64(9)

In [53]:
arr.min()

np.int64(0)

In [55]:
arr.std()

np.float64(2.8722813232690143)

In [60]:
arr2d = np.arange(25).reshape(5,5)

In [62]:
arr2d.shape

(5, 5)

In [64]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
arr2d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [66]:
arr3d = np.arange(1,28).reshape((3,3,3))

In [69]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [79]:
arr3d[:,::2,::2]

array([[[ 1,  3],
        [ 7,  9]],

       [[10, 12],
        [16, 18]],

       [[19, 21],
        [25, 27]]])

In [72]:
arr3d[1:,::2,1]

array([[11, 17],
       [20, 26]])

In [68]:
arr3d[2,1:,1:]

array([[23, 24],
       [26, 27]])

In [70]:
arr3d[1:,::2,::2]

array([[[10, 12],
        [16, 18]],

       [[19, 21],
        [25, 27]]])

In [73]:
arr = np.arange(1,33).reshape((4,8))

# Advance Numpy

# fancy_indexing

In [84]:
a = np.arange(1,25).reshape(6,4)

In [85]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [87]:
a[:,[0,2,3]]

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12],
       [13, 15, 16],
       [17, 19, 20],
       [21, 23, 24]])

In [86]:
a[[1,2,5]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [21, 22, 23, 24]])

# boolean_indexing

In [108]:
a = np.random.randint(1,100,24).reshape(6,4)

In [109]:
a

array([[44,  8, 47, 35],
       [78, 81, 36, 50],
       [ 4,  2,  6, 54],
       [ 4, 54, 93, 63],
       [18, 90, 44, 34],
       [74, 62, 14, 95]], dtype=int32)

In [110]:
#A in greater than 50
a > 50

array([[False, False, False, False],
       [ True,  True, False, False],
       [False, False, False,  True],
       [False,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True, False,  True]])

In [111]:
a[a>50]

array([78, 81, 54, 54, 93, 63, 90, 74, 62, 95], dtype=int32)

In [112]:
a[a%2 == 0]

array([44,  8, 78, 36, 50,  4,  2,  6, 54,  4, 54, 18, 90, 44, 34, 74, 62,
       14], dtype=int32)

In [113]:
#find all number greater than 50 and even
a[(a>50) & (a%2 == 0)]

array([78, 54, 54, 90, 74, 62], dtype=int32)

In [118]:
#find all the number not divisible by 7
a[a%7 != 0]

array([44,  8, 47, 78, 81, 36, 50,  4,  2,  6, 54,  4, 54, 93, 18, 90, 44,
       34, 74, 62, 95], dtype=int32)

In [119]:
a[~(a%7 == 0)]

array([44,  8, 47, 78, 81, 36, 50,  4,  2,  6, 54,  4, 54, 93, 18, 90, 44,
       34, 74, 62, 95], dtype=int32)

 ## Broadcasting

In [128]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [129]:
b = np.arange(2).reshape(2)
b

array([0, 1])

In [130]:
a + b

ValueError: operands could not be broadcast together with shapes (4,3) (2,) 

In [132]:
# More examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)
#broadcasting is possible

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [137]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

print(a+b)
#broadcasting is not possible

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [138]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)
#broadcasting is possible

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [139]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)
#broadcasting is possible

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [140]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)
#broadcasting is possible

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [141]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)
#broadcasting is possible

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [142]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)
#broadcasting is not possible

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 