In [3]:
import numpy as np

In [5]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [6]:
mylist = [[1,2,3],[3,4,5],[6,7,8]]

In [7]:
np.array(mylist)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [9]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [12]:
np.random.randint(1,10,10)

array([7, 3, 7, 8, 5, 4, 8, 8, 3, 6], dtype=int32)

In [13]:
np.random.binomial(1,2,3)

ValueError: p < 0, p > 1 or p is NaN

In [14]:
import numpy as np
myarray = np.linspace(0,10,101)

In [15]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [16]:
array = np.arange(0,11)

In [17]:
array[:3] = 2

In [18]:
array_copy = array.copy()

In [19]:
array

array([ 2,  2,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
nex = array_copy[array >4]

In [21]:
array_copy

array([ 2,  2,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
array_copy  < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False])

In [23]:
array_2d = np.array([[3,4,5],[6,7,8],[9,10,11]])

In [24]:
array_2d[2]

array([ 9, 10, 11])

In [25]:
array_2d[::-1]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 3,  4,  5]])

In [26]:
#numpy_operation

In [29]:
arr = np.arange(0,10)

In [30]:
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
arr - 5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [33]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [34]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [36]:
arr/arr

C:\Users\user\AppData\Local\Temp\ipykernel_16964\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [39]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [41]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [42]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [43]:
np.log(arr)

C:\Users\user\AppData\Local\Temp\ipykernel_16964\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [48]:
arr = np.arange(10)

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr.sum()

np.int64(45)

In [52]:
arr.max()

np.int64(9)

In [53]:
arr.min()

np.int64(0)

In [55]:
arr.std()

np.float64(2.8722813232690143)

In [36]:
arr2d = np.arange(25).reshape(5,5)

In [37]:
arr2d.shape

(5, 5)

In [47]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arr2d[2:3,2:3]

array([[12]])

In [50]:
arr3d = np.arange(1,28).reshape((3,3,3))

In [51]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [79]:
arr3d[:,::2,::2]

array([[[ 1,  3],
        [ 7,  9]],

       [[10, 12],
        [16, 18]],

       [[19, 21],
        [25, 27]]])

In [72]:
arr3d[1:,::2,1]

array([[11, 17],
       [20, 26]])

In [68]:
arr3d[2,1:,1:]

array([[23, 24],
       [26, 27]])

In [70]:
arr3d[1:,::2,::2]

array([[[10, 12],
        [16, 18]],

       [[19, 21],
        [25, 27]]])

In [73]:
arr = np.arange(1,33).reshape((4,8))

# Advance Numpy

# fancy_indexing

In [84]:
a = np.arange(1,25).reshape(6,4)

In [85]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [87]:
a[:,[0,2,3]]

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12],
       [13, 15, 16],
       [17, 19, 20],
       [21, 23, 24]])

In [86]:
a[[1,2,5]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [21, 22, 23, 24]])

# boolean_indexing

In [108]:
a = np.random.randint(1,100,24).reshape(6,4)

In [109]:
a

array([[44,  8, 47, 35],
       [78, 81, 36, 50],
       [ 4,  2,  6, 54],
       [ 4, 54, 93, 63],
       [18, 90, 44, 34],
       [74, 62, 14, 95]], dtype=int32)

In [110]:
#A in greater than 50
a > 50

array([[False, False, False, False],
       [ True,  True, False, False],
       [False, False, False,  True],
       [False,  True,  True,  True],
       [False,  True, False, False],
       [ True,  True, False,  True]])

In [111]:
a[a>50]

array([78, 81, 54, 54, 93, 63, 90, 74, 62, 95], dtype=int32)

In [112]:
a[a%2 == 0]

array([44,  8, 78, 36, 50,  4,  2,  6, 54,  4, 54, 18, 90, 44, 34, 74, 62,
       14], dtype=int32)

In [113]:
#find all number greater than 50 and even
a[(a>50) & (a%2 == 0)]

array([78, 54, 54, 90, 74, 62], dtype=int32)

In [118]:
#find all the number not divisible by 7
a[a%7 != 0]

array([44,  8, 47, 78, 81, 36, 50,  4,  2,  6, 54,  4, 54, 93, 18, 90, 44,
       34, 74, 62, 95], dtype=int32)

In [119]:
a[~(a%7 == 0)]

array([44,  8, 47, 78, 81, 36, 50,  4,  2,  6, 54,  4, 54, 93, 18, 90, 44,
       34, 74, 62, 95], dtype=int32)

 ## Broadcasting

In [128]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [129]:
b = np.arange(2).reshape(2)
b

array([0, 1])

In [130]:
a + b

ValueError: operands could not be broadcast together with shapes (4,3) (2,) 

In [132]:
# More examples

a = np.arange(12).reshape(4,3)
b = np.arange(3)

print(a)
print(b)

print(a+b)
#broadcasting is possible

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [137]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)

print(a)
print(b)

print(a+b)
#broadcasting is not possible

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [138]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print(a+b)
#broadcasting is possible

[[0 1 2]]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [139]:
a = np.arange(3).reshape(1,3)
b = np.arange(4).reshape(4,1)

print(a)
print(b)

print(a + b)
#broadcasting is possible

[[0 1 2]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [140]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)
#broadcasting is possible

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [141]:
a = np.array([1])
# shape -> (1,1)
b = np.arange(4).reshape(2,2)
# shape -> (2,2)

print(a)
print(b)

print(a+b)
#broadcasting is possible

[1]
[[0 1]
 [2 3]]
[[1 2]
 [3 4]]


In [142]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)
#broadcasting is not possible

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [32]:
a = np.arange(8)

In [33]:
b = np.arange(0,16,2)

In [34]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [54]:
c = b + a

In [55]:
c

array([ 0,  3,  6,  9, 12, 15, 18, 21])

# Revision
Date - 9/9/26

In [294]:
#lecture 1

In [3]:
import numpy as np

In [14]:
lst = [[1,2,3,4,5,6,7,8,9],[10,11,12,13,14,15,16,17,18]]

In [19]:
np.array(lst).reshape(3,3)

ValueError: cannot reshape array of size 18 into shape (3,3)

In [33]:
np.arange(1,28).reshape(3,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [37]:
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [71]:
np.linspace(0,20,4
           )

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [149]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [153]:
np.random.seed(42)
np.random.rand(5,5)


array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998]])

In [133]:
np.random.seed(42)
np.random.randint(1,17,(4,4))

array([[ 7,  4, 13, 15],
       [11,  8, 13,  5],
       [ 7, 10,  3,  7],
       [11, 11,  8,  5]], dtype=int32)

In [160]:
np.random.randn(2,2)

array([[-0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473]])

In [161]:
np.random.randn(4).reshape(2,2)

array([[-0.46947439,  0.54256004],
       [-0.46341769, -0.46572975]])

In [201]:
num = np.random.randint(1,17,10)
num

array([ 8, 12,  2,  1, 16,  7,  7, 14,  8,  5], dtype=int32)

In [202]:
num.max()

np.int32(16)

In [203]:
num.min()

np.int32(1)

In [207]:
# Use to find the index number of max 
num.argmax()

np.int64(4)

In [210]:
# Use to find the index number of min 
num.argmin()

np.int64(3)

In [218]:
# If want to know the datatype
num.dtype

dtype('int32')

In [258]:
# if want know the shape of variable
num.shape

(10,)

In [259]:
#lec second

In [260]:
arr = np.arange(0,11)

In [261]:
arr2 = arr[:5]

In [262]:
arr2[:] = 100

In [263]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [264]:
#if we dont want change the original array then we can use the copy function

In [265]:
arr = np.arange(0,11)

In [266]:
arr_copy = arr.copy()

In [267]:
arr_copy2 = arr_copy[:5]

In [268]:
arr_copy2[:] = 100

In [269]:
arr_copy2

array([100, 100, 100, 100, 100])

In [270]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [271]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [284]:
# indexing and slicing is 2d array

In [273]:
array_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [274]:
array_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [280]:
array_2d[0]

array([ 5, 10, 15])

In [282]:
array_2d[0,1]

np.int64(10)

In [283]:
array_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [285]:
#Appling coditinal operator on arrays

In [286]:
arr = np.arange(0,11)

In [287]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [288]:
arr >1

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [289]:
arr ==6

array([False, False, False, False, False, False,  True, False, False,
       False, False])

In [290]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [291]:
len(arr)

11

In [292]:
# Lectur 3

In [295]:
arr = np.arange(0,10)

In [297]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [301]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [298]:
arr.sum()

np.int64(45)

In [299]:
arr.mean()

np.float64(4.5)

In [300]:
arr.var()

np.float64(8.25)

In [302]:
arr.std()

np.float64(2.8722813232690143)

In [310]:
#If i want to perform any of these operation of perticular rows or coloums then we can use


array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

In [314]:
arr = np.arange(0,25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [316]:
arr.std(axis = 0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [317]:
arr.sum(1)

array([ 10,  35,  60,  85, 110])

In [319]:
arr.sum(0)

array([50, 55, 60, 65, 70])

Create an array of all the even integers from 10 to 50

In [320]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x3 matrix with values ranging from 0 to 8

In [322]:
np.random.randint(0,9,(3,3))

array([[2, 7, 5],
       [2, 0, 2],
       [4, 2, 0]], dtype=int32)

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

  NOTE: Your result's values should be different from the ones shown below.

In [323]:
np.random.randn(25)

array([-0.93376284,  0.78420819, -0.61487576,  0.33289244, -1.38071702,
       -0.28080629, -0.05981726,  0.96117377,  1.79428084,  0.58068954,
        0.29765045, -1.02811577, -1.41859646,  0.19033698,  0.13575383,
        0.60808966,  0.70498131,  0.36092338, -1.46696789,  0.89262947,
       -0.10525713, -0.95534644, -0.41476463, -1.39874088, -0.34408054])

Create an array of 20 linearly spaced points between 0 and 1:

In [324]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

13. Write code that reproduces the output shown below.

  Be careful not to run the cell immediately above the output, otherwise you won't be able to see the output any more.