In [3]:
import numpy as np

In [4]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [7]:
mylist = [[1,2,3],[3,4,5],[6,7,8]]

In [8]:
np.array(mylist)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [15]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.linspace(2,10,5)

array([ 2.,  4.,  6.,  8., 10.])

In [27]:
np.random.randint(1,10,10)

array([1, 3, 7, 4, 9, 3, 5, 3, 7, 5], dtype=int32)

In [33]:
np.random.binomial(1,2,3)

ValueError: p < 0, p > 1 or p is NaN

In [34]:
import numpy as np
myarray = np.linspace(0,10,101)

In [35]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [45]:
array = np.arange(0,11)

In [47]:
array[:3] = 2

In [46]:
array_copy = array.copy()

In [48]:
array

array([ 2,  2,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
nex = array_copy[array >4]

In [60]:
array_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
array_copy  < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False])

In [63]:
array_2d = np.array([[3,4,5],[6,7,8],[9,10,11]])

In [78]:
array_2d[2]

array([ 9, 10, 11])